name: Mirror to Lumiq

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Lumiq internal repo
        env:
          LUMIQ_USER: ${{ secrets.LUMIQ_USER }}
          LUMIQ_PASS: ${{ secrets.LUMIQ_PASS }}
        run: |
          git config --global http.sslVerify false
          git remote add lumiq https://${LUMIQ_USER}:${LUMIQ_PASS}@codebase.aps1aws.lumiq.int/Lumiq-Org/Easy-Tracker.git
          git push lumiq main --force
